# Generated by Django 4.0.2 on 2022-02-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pin', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('Tikapur', 'Tikapur'), ('kathmandu', 'kathmandu'), ('Pokhara', 'Pokhara'), ('Jhapa', 'Jhapa'), ('Ilam', 'Ilam'), ('Achham', 'Achham'), ('Npljung', 'Npljung'), ('Bardia', 'Bardia')], max_length=100)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, upload_to='profileimg')),
                ('my_file', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
