# Generated by Django 4.0.2 on 2022-02-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResumeModel',
            new_name='Resume',
        ),
    ]
